# permissions for end users to view databases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: database-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pgdb
    app.kubernetes.io/part-of: pgdb
    app.kubernetes.io/managed-by: kustomize
  name: database-viewer-role
rules:
- apiGroups:
  - pgdb.storage.meschbach.com
  resources:
  - databases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pgdb.storage.meschbach.com
  resources:
  - databases/status
  verbs:
  - get
