---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgdb.storage.meschbach.com
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgdb.storage.meschbach.com
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - pgdb.storage.meschbach.com
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pgdb.storage.meschbach.com
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgdb.storage.meschbach.com
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - pgdb.storage.meschbach.com
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
