apiVersion: pgdb.storage.meschbach.com/v1alpha1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/instance: database-sample
    app.kubernetes.io/part-of: pgdb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pgdb
  name: database-sample
spec:
  clusterNamespace: "dev-pg-16-0"
  clusterSecret: "pgdb-example-secret"
  databaseSecret: "pgdb-output"
  controller: "test"
