name: onRelease

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unit Tests
        run: |
          make test build
  release:
    runs-on: ubuntu-latest
    needs: [unit_tests]
    if: github.triggering_actor == 'meschbach'
    timeout-minutes: 5
    # needed for version bumping
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Multiplatform build file
        run: |
          make docker-buildx-edit
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          platforms: "linux/amd64,linux/arm64"
          file: Dockerfile.cross
          push: true
          tags: |
            meschbach/pgdb:latest
            meschbach/pgdb:main
            meschbach/pgdb:${{ github.sha }}
            meschbach/pgdb:${{ steps.version.outputs.tag }}
      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          generate_release_notes: true
